# -*- coding: utf-8 -*-
"""bubbleSort.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ucV7oBSqPzO6Pd4KaC3NpF4d4OznrvI6
"""

from random import randint
import timeit
import matplotlib as mpl
import matplotlib.pyplot as plt
 
def geraLista(tam):
    lista = []
    for i in range(tam):
        n = randint(1,1*tam)
        if n not in lista: lista.append(n)
    return lista
 
# x = Tempo de ordenação  e o Y = tamanho da lista de numeros
 
def desenhaGrafico(x,y,XAxis = "Lista de Numeros", YAxis = "Tempo de ordenação"):
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111)
    ax.plot(x,y, label = "Lista de Numeros")
    ax.legend(bbox_to_anchor=(1, 1),bbox_transform=plt.gcf().transFigure)
    plt.ylabel(YAxis)
    plt.xlabel(XAxis)
    fig.savefig(YAxis)
    plt.show()



def bubbleSort(elementList):
    numberSwap = 0
    swapped = True
    while swapped:
        swapped = False
        lenghtList = len(elementList)
        for i in range (lenghtList - 1): #tamanho da lista    
            if elementList[i] > elementList[i+1] :
                elementList[i], elementList[i+1] = elementList[i+1], elementList[i]
                swapped = True
                numberSwap = numberSwap + 1
        if swapped == False:
            return numberSwap


value10k = 10000
value20k = 20000
value50k = 50000
value100k = 100000
list10k = geraLista(value10k)
list20k = geraLista(value20k)
list50k = geraLista(value50k)
list100k = geraLista(value100k)

listValue = [value10k,value20k,value50k,value100k]
listQuestion = [list10k,list20k,list50k,list100k]
timeSort = []
listNumberSwap = []

for i in range(4):
    timeSort.append(timeit.timeit("bubbleSort({})".format(listQuestion[i]),setup="from __main__ import geraLista,bubbleSort",number = 1))
    listNumberSwap.append(bubbleSort(listQuestion[i]))


desenhaGrafico(listValue,timeSort, XAxis="Número de elementos", YAxis="Tempo de ordenação em Seg")
desenhaGrafico(listValue,listNumberSwap, XAxis="Número de elementos", YAxis="Numero de Trocas")